#!/bin/bash
file="times"
for ((i=1; i<=15; i++))
do
for var in $(cat $file)
do
./lab1-sol-par-1 $var >> log_sol-1
./lab1-sol-par-2 $var >> log_sol-2
./lab1-sol-par-4 $var >> log_sol-4
./lab1-sol-par-6 $var >> log_sol-6
done
done
for ((i=1; i<=5; i++))
do
for var in $(cat $file)
do
./lab1-sol-par-1-X $var >> log_sol-1-X
./lab1-sol-par-2-X $var >> log_sol-2-X
./lab1-sol-par-4-X $var >> log_sol-4-X
./lab1-sol-par-6-X $var >> log_sol-6-X
done
done
